#!/usr/bin/env python3
"""
Regenerate the "graph today" numbers in the README.

Building in public only works if the number is real, and a number maintained by
hand drifts the moment it is inconvenient. This writes the live graph state into
the README between two markers, so the public claim is generated rather than
asserted.

    python scripts/graph_stats.py           # update README.md in place
    python scripts/graph_stats.py --print   # just show the numbers

Run it after a watch fires, or on a schedule. If the number is small, it prints
small. That is the point: at this stage the honesty is the differentiation.

No em dashes.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "api"))

START = "<!-- GRAPH_STATS:START -->"
END = "<!-- GRAPH_STATS:END -->"


def build():
    import _graph as G
    import _deliver as D

    c = G.counts()
    by = c["by_type"]
    v = D.value()

    sourced = 0
    total = 0
    for t in ("signal", "person"):
        for n in G.query(t, limit=2000):
            total += 1
            if n.get("source") or n.get("agent"):
                sourced += 1
    pct = round(100.0 * sourced / total) if total else 100

    rows = [
        ("Signals", by.get("signal", 0), "public posts, each with a link back to the original"),
        ("People", by.get("person", 0), "authors resolved from those posts"),
        ("Outcomes", by.get("outcome", 0), "alerts a human marked actioned, ignored, or converted"),
        ("Cohorts", by.get("cohort", 0), "live segments, membership recomputed on every read"),
        ("Definitions", by.get("definition", 0), "authoritative metric definitions"),
        ("Agent runs", by.get("run", 0), "every one replayable, every step traced"),
        ("Decisions", by.get("action", 0), "approval requests, each carrying the rule that answered it"),
    ]

    out = [START, "",
           f"**{c['nodes']} nodes, {c['edges']} edges.** Generated by "
           "`scripts/graph_stats.py`, not typed by hand.", "",
           "| | Count | What it is |", "|---|---|---|"]
    for name, n, desc in rows:
        out.append(f"| {name} | **{n}** | {desc} |")
    out += ["",
            f"**{pct}% of nodes carry provenance** (which agent wrote it, in which run, from what source). "
            "The target is 100, and anything below it is a bug.", "",
            f"Value to date: *{v['sentence']}*", "",
            "This number is small. It is supposed to be, at this stage. A graph that "
            "starts big was bought, and a bought graph is the one thing this is not.",
            "", END]
    return "\n".join(out)


def main():
    block = build()
    if "--print" in sys.argv:
        print(block)
        return 0
    p = os.path.join(ROOT, "README.md")
    s = open(p, encoding="utf-8").read()
    if START not in s or END not in s:
        print(f"markers not found in README.md; add {START} / {END}")
        return 1
    head, rest = s.split(START, 1)
    _, tail = rest.split(END, 1)
    open(p, "w", encoding="utf-8").write(head + block + tail)
    print("README.md graph stats updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
